problem statement 1 :- 

Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.
_______________________________________________________________________________________________________________________________

In [1]:
def Matrix(a , N) :
    matrix = np.column_stack([a**(N-i-1) for i in range(N)])
    print("AlexandreTheophile Vandermonde matrix for " , a ," :")
    print(matrix)
import numpy as np
a = np.arange(1,6)
N = len(a)
Matrix(a,N)

AlexandreTheophile Vandermonde matrix for  [1 2 3 4 5]  :
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

____________________________________________________________________________________________________________________


In [2]:
def Average (a , k = 3) :
    n = len(a)
    av = []
    for i in range(n-k+1) :
        av.append(sum(np.ones(k) * a[i : i+k]) / k)
    print ("\n",av)
import numpy as np 
a = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
print("Input array :",a)
print("\nMoving average in an array over a window 3 :")
Average(a , k = 3)

Input array : [  3   5   7   2   8  10  11  65  72  81  99 100 150]

Moving average in an array over a window 3 :

 [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
