# Problem Statement 1:

In each of the following situations, state whether it is a correctly stated hypothesis testing problem and why?

1. 𝐻0: 𝜇 = 25, 𝐻1: 𝜇 ≠ 25
        
2. 𝐻0: 𝜎 > 10, 𝐻1: 𝜎 = 10
        
3. 𝐻0: 𝑥 = 50, 𝐻1: 𝑥 ≠ 50
        
4. 𝐻0: 𝑝 = 0.1, 𝐻1: 𝑝 = 0.5
        
5. 𝐻0: 𝑠 = 30, 𝐻1: 𝑠 > 30

##### Answer :
(1) , (3) , (5)  is a correctly stated hypothesis testing problem because null hypothesis states that there is no difference between a hypothesized
population mean and a sample mean.

# Problem Statement 2:

The college bookstore tells prospective students that the average cost of its
textbooks is Rs. 52 with a standard deviation of Rs. 4.50. A group of smart statistics
students thinks that the average cost is higher. To test the bookstore’s claim against
their alternative, the students will select a random sample of size 100. Assume that
the mean from their random sample is Rs. 52.80. Perform a hypothesis test at the
5% level of significance and state your decision.

##### Answer :
Average cost of its textbooks(𝜇) = Rs. 52 

Standard deviation (𝜎) =  Rs. 4.50

Random sample of size(n) = 100

Mean of random sample (x¯) = Rs. 52.80

level of significance (alpha) = 0.05

Null Hypothesis (𝐻0) : 𝜇 = 52 

Alternate Hypothesis (𝐻1) : 𝜇 != 52

In [1]:
import numpy as np

In [2]:
def Ztest(s_mean , p_mean , n , std):
    return (s_mean - p_mean)/(std / np.sqrt(n))

In [3]:
s_mean = 52.80
p_mean = 52
n = 100
std = 4.50
z_value = Ztest(s_mean , p_mean , n , std)
print(z_value)

1.7777777777777715


We use significance level α = 0.05, but because of a two-sided test we have two rejection regions. They are z < −1.96 or z > 1.96..

In [4]:
if z_value > 1.96 or z_value < -1.96  :
    print("We Reject the Null Hypothesis(HO)")
else :
    print("We Do Not Reject The Null Hypothesis(HO)")

We Do Not Reject The Null Hypothesis(HO)


We accept the Null Hypothesis , Hence the mean average cost of textbook is Rs. 52

# Problem Statement 3:

A certain chemical pollutant in the Genesee River has been constant for several
years with mean μ = 34 ppm (parts per million) and standard deviation σ = 8 ppm. A
group of factory representatives whose companies discharge liquids into the river is
now claiming that they have lowered the average with improved filtration devices. A
group of environmentalists will test to see if this is true at the 1% level of
significance. Assume \ that their sample of size 50 gives a mean of 32.5 ppm.
Perform a hypothesis test at the 1% level of significance and state your decision.

###### Answer :

mean (𝜇) = 34 ppm

Standard deviation (𝜎) = 8 ppm

Random sample of size(n) = 50

Mean of random sample (x¯) = 32.5 ppm

level of significance (alpha) = 0.01

Null Hypothesis (𝐻0) : 𝜇 = 34 ppm

Alternate Hypothesis (𝐻1) : 𝜇 < 34 ppm

In [5]:
import numpy as np

In [6]:
def Ztest(s_mean , p_mean , n , std):
    return (s_mean - p_mean)/(std / np.sqrt(n))

In [7]:
s_mean = 32.5
p_mean = 34
n = 50
std = 8
z_value = Ztest(s_mean , p_mean , n , std)
print(z_value)

-1.3258252147247767


we use level of significance (alpha) = 0.01, therefore the rejection region is when z_value < -2.326.

In [8]:
if z_value < -2.326 :
    print("We Reject the Null Hypothesis(HO)")
else :
    print("We Do Not Reject The Null Hypothesis(HO)")

We Do Not Reject The Null Hypothesis(HO)


We accept the Null Hypothesis, Hence we claim that they have lowered the average with improved filtration devices

# Problem Statement 4:

Based on population figures and other general information on the U.S. population,
suppose it has been estimated that, on average, a family of four in the U.S. spends
about $1135 annually on dental expenditures. Suppose further that a regional dental
association wants to test to determine if this figure is accurate for their area of
country. To test this, 22 families of 4 are randomly selected from the population in
that area of the country and a log is kept of the family’s dental expenditure for one
year. The resulting data are given below. Assuming, that dental expenditure is
normally distributed in the population, use the data and an alpha of 0.5 to test the
dental association’s hypothesis.
1008, 812, 1117, 1323, 1308, 1415, 831, 1021, 1287, 851, 930, 730, 699,
872, 913, 944, 954, 987, 1695, 995, 1003, 994

##### Answer :

population mean (𝜇) = $1135

Random sample of size(n) = 22

level of significance (alpha) = 0.5

Null Hypothesis (𝐻0) : 𝜇 = $1135

Alternate Hypothesis (𝐻1) : 𝜇 != $1135

In [9]:
import numpy as np
from scipy.stats import ttest_1samp

In [10]:
sample_data = [1008, 812, 1117, 1323, 1308, 1415, 831, 1021, 1287, 851, 930, 730, 699, 872, 913, 944, 954, 987, 1695, 995, 1003, 994]

In [11]:
p_mean = 1135
ttest_value , p_value = ttest_1samp(sample_data , p_mean)

In [12]:
print("T value :",ttest_value)
print("p value :",p_value)

T value : -2.023137479931484
p value : 0.0559738319464585


In [13]:
if p_value < 0.5 :
    print("Reject Null Hypothesis")
else :
    print("Accept Null Hypothesis")

Reject Null Hypothesis


# Problem Statement 5:

In a report prepared by the Economic Research Department of a major bank the
Department manager maintains that the average annual family income on Metropolis
is $48,432. What  do you conclude about the validity of the report if a random sample
of 400 families shows and average income of $48,574  with a standard deviation of
2000?

##### Answer :

population mean (𝜇) = 48432 

Standard deviation (𝜎) = 2000

Random sample of size(n) = 400

Mean of random sample (x¯) = 48574 

level of significance (alpha) = 0.05

Null Hypothesis (𝐻0) : 𝜇 = 48432

Alternate Hypothesis (𝐻1) : 𝜇 != 48432

In [14]:
import numpy as np

In [15]:
def Ztest(s_mean , p_mean , n , std):
    return (s_mean - p_mean)/(std / np.sqrt(n))

In [16]:
s_mean = 48574
p_mean = 48432
n = 400
std = 2000
z_value = Ztest(s_mean , p_mean , n , std)
print("Z value : ",z_value)

Z value :  1.42


We use significance level α = 0.05, but because of a two-sided test we have two rejection regions. They are z < −1.96 or z > 1.96..

In [17]:
if z_value > 1.96 or z_value < -1.96  :
    print("We Reject the Null Hypothesis(HO)")
else :
    print("We Do Not Reject The Null Hypothesis(HO)")

We Do Not Reject The Null Hypothesis(HO)


# Problem Statement 6:

##### Answer :

population mean (𝜇) = 32.28

Standard deviation (𝜎) = 1.29

Random sample of size(n) = 19

Mean of random sample (x¯) = 31.67

level of significance (alpha) = 0.05

Null Hypothesis (𝐻0) : 𝜇 = 32.28

Alternate Hypothesis (𝐻1) : 𝜇 != 32.28

In [18]:
import numpy as np

In [19]:
def Ztest(s_mean , p_mean , n , std):
    return (s_mean - p_mean)/(std / np.sqrt(n))

In [20]:
s_mean = 31.67
p_mean = 32.28
n = 19
std = 1.29
z_value = Ztest(s_mean , p_mean , n , std)
print("Z value : ",z_value)

Z value :  -2.06118477175179


We use significance level α = 0.05, but because of a two-sided test we have two rejection regions. They are z < −1.96 or z > 1.96..

In [21]:
if z_value > 1.96 or z_value < -1.96  :
    print("We Reject the Null Hypothesis(HO)")
else :
    print("We Do Not Reject The Null Hypothesis(HO)")

We Reject the Null Hypothesis(HO)


We Reject the Null Hypothesis, Hence the average price per square foot for warehouse has changed now.

# Problem Statement 7:

Fill in the blank spaces in the table and draw your conclusions from it.

# Problem Statement 8:

Find the t-score for a sample size of 16 taken from a population with mean 10 when
the sample mean is 12 and the sample standard deviation is 1.5.

##### Answer :

population mean (𝜇) = 10

Sample standard deviation (s) = 1.5

Random sample of size(n) = 16

Mean of random sample (x¯) = 12

In [22]:
import numpy as np

In [23]:
def Ttest(s_mean , p_mean , n , s_std):
    return (s_mean - p_mean)/(s_std / np.sqrt(n))

In [24]:
s_mean = 12
p_mean = 10
n = 16
s_std = 1.5
T_Score = Ttest(s_mean , p_mean , n , std)
print("T_Score value : ",T_Score)

T_Score value :  6.201550387596899


# Problem Statement 9:

Find the t-score below which we can expect 99% of sample means will fall if samples
of size 16 are taken from a normally distributed population.

##### Answer :

Sample size (n) =  16

confident Interval = 99%

degree of freedom (dof) = n -1
                        = 16 - 1 = 15

t-score at 99% = -(t-score at 1%)

As t-score at 1% = 2.602

Therefore, t-score at 99% = -2.602

# Problem Statement 10:

If a random sample of size 25 drawn from a normal population gives a mean of 60
and a standard deviation of 4, find the range of t-scores where we can expect to find
the middle 95% of all sample means. Compute the probability that (−𝑡0.05 <𝑡<𝑡0.10).

##### Answer :

Sample size (n) = 25

mean (x) = 60

Standard Deviation = 4

confidence interval = 95%
=> alpha = 0.05

therefore z value at alpha/2 = 1.96

In [25]:
import numpy as np

def limit(mean,std,n):
    lower_limit = mean - 1.96 * (std / np.sqrt(n))
    upper_limit = mean + 1.96 * (std / np.sqrt(n))
    return lower_limit , upper_limit

In [26]:
Range = limit(mean = 60 , std = 4 , n = 25)
print("The range of t-scores where we can expect to find the middle 95% of all sample means : ",Range)

The range of t-scores where we can expect to find the middle 95% of all sample means :  (58.432, 61.568)


# Problem Statement 11:

Two-tailed test for difference between two population means
Is there evidence to conclude that the number of people travelling from Bangalore to
Chennai is different from the number of people travelling from Bangalore to Hosur in
a week, given the following:
    
Population 1: Bangalore to Chennai 
n1 = 1200
x1 = 452
s1 = 212

Population 2: Bangalore to Hosur 
n2 = 800
x2 = 523
s2 = 185

Null Hypothesis : 𝜇1 = 𝜇2
    
Alternate Hypothesis : 𝜇1 != 𝜇2

In [27]:
import numpy as np

In [28]:
def two_sample_test(x1,x2,SE):
    return (x1-x2)/SE

In [29]:
x1 = 452
s1 = 212
n1 = 1200
x2 = 523
s2 = 185
n2 = 800
SE = np.sqrt((s1**2 / n1) + (s2**2 / n2))
z_value = two_sample_test(x1,x2,SE)
print("Z Value : ",z_value)

Z Value :  -7.926428526759299


We use significance level α = 0.05, but because of a two-sided test we have two rejection regions. They are z < −1.96 or z > 1.96..

In [30]:
if z_value > 1.96 or z_value < -1.96  :
    print("We Reject the Null Hypothesis(HO)")
else :
    print("We Do Not Reject The Null Hypothesis(HO)")

We Reject the Null Hypothesis(HO)


Hence the number of people travelling from Bangalore to Chennai is different from the number of people travelling from Bangalore to Hosur in a week

# Problem Statement 12:

Is there evidence to conclude that the number of people preferring Duracell battery is
different from the number of people preferring Energizer battery, given the following:
    
Population 1: Duracell
n1 = 100
x1 = 308
s1 = 84

Population 2: Energizer
n2 = 100
x2 = 254
s2 = 67

Null Hypothesis : 𝜇1 = 𝜇2

Alternate Hypothesis : 𝜇1 != 𝜇2

In [31]:
import numpy as np

In [32]:
def two_sample_test(x1,x2,SE):
    return (x1-x2)/SE

In [33]:
x1 = 308
s1 = 84
n1 = 100
x2 = 254
s2 = 67
n2 = 100
SE = np.sqrt((s1**2 / n1) + (s2**2 / n2))
z_value = two_sample_test(x1,x2,SE)
print("Z Value : ",z_value)

Z Value :  5.025702668336442


We use significance level α = 0.05, but because of a two-sided test we have two rejection regions. They are z < −1.96 or z > 1.96..

In [34]:
if z_value > 1.96 or z_value < -1.96  :
    print("We Reject the Null Hypothesis(HO)")
else :
    print("We Do Not Reject The Null Hypothesis(HO)")

We Reject the Null Hypothesis(HO)


Hence the number of people preferring Duracell battery is different from the number of people preferring Energizer battery

# Problem Statement 13:

Pooled estimate of the population variance
Does the data provide sufficient evidence to conclude that average percentage
increase in the price of sugar differs when it is sold at two different prices?

Population 1: Price of sugar = Rs. 27.50
    
n1 = 14
x1 = 0.317%
s1 = 0.12%

Population 2: Price of sugar = Rs. 20.00 

n2 = 9
x2 = 0.21%
s2 = 0.11%

Null Hypothesis : 𝜇1 = 𝜇2

Alternate Hypothesis : 𝜇1 != 𝜇2

In [35]:
import numpy as np

In [36]:
def two_sample_test(x1,x2,SE): # for T-test
    return abs((x1-x2))/SE

In [37]:
x1 = 0.317
s1 = 0.12
n1 = 14
x2 = 0.21
s2 = 0.11
n2 = 9
s12 = np.sqrt(((((n1-1)*(s1**2)) + ((n2-1)*(s2**2))))/(n1+n2-2))
SE = s12 * np.sqrt((1 / n1) + (1 / n2))
t_value = two_sample_test(x1,x2,SE)
print("T Value : ",t_value)

T Value :  2.15355322387416


In [38]:
dof = n1+n2-2 # degree of freedom
print("degree of freedom : ",dof)

degree of freedom :  21


We use significance level α = 0.05, but because of a two-sided test we have two rejection regions. They are t < −2.080 or t > 2.080 at degree of freedom = 21.

In [39]:
if t_value > 2.080 or t_value < -2.080  :
    print("We Reject the Null Hypothesis(HO)")
else :
    print("We Do Not Reject The Null Hypothesis(HO)")

We Reject the Null Hypothesis(HO)


Hence average percentage increase in the price of sugar differs when it is sold at two different prices.

# Problem Statement 14:

The manufacturers of compact disk players want to test whether a small price
reduction is enough to increase sales of their product. Is there evidence that the
small price reduction is enough to increase sales of compact disk players?

Population 1: Before reduction

n1 = 15
x1 = Rs. 6598 
s1 = Rs. 844

Population 2: After reduction 

n2 = 12
x2 = RS. 6870
s2 = Rs. 669

Null Hypothesis : 𝜇1 = 𝜇2

Alternate Hypothesis : 𝜇1 != 𝜇2

In [40]:
import numpy as np

In [41]:
def two_sample_test(x1,x2,SE): # for T-test
    return abs((x1-x2))/SE

In [42]:
x1 = 6598
s1 = 844
n1 = 15
x2 = 6870
s2 = 669
n2 = 12
s12 = np.sqrt(((((n1-1)*(s1**2)) + ((n2-1)*(s2**2))))/(n1+n2-2))
SE = s12 * np.sqrt((1 / n1) + (1 / n2))
t_value = two_sample_test(x1,x2,SE)
print("T Value : ",t_value)

T Value :  0.9098300343990459


In [43]:
dof = n1+n2-2 # degree of freedom
print("degree of freedom : ",dof)

degree of freedom :  25


We use significance level α = 0.05, but because of a two-sided test we have two rejection regions. They are t < −2.060 or t > 2.060 at degree of freedom = 25.

In [44]:
if t_value > 2.060 or t_value < -2.060  :
    print("We Reject the Null Hypothesis(HO)")
else :
    print("We Do Not Reject The Null Hypothesis(HO)")

We Do Not Reject The Null Hypothesis(HO)


Hence he small price reduction is not enough to increase sales of compact disk players

# Problem Statement 15:

Comparisons of two population proportions when the hypothesized difference is zero
Carry out a two-tailed test of the equality of banks’ share of the car loan market in
1980 and 1995.

Population 1: 1980

n1 = 1000
x1 = 53
𝑝1 = 0.53

Population 2: 1985

n2 = 100
x2 = 43
𝑝2= 0.53

Null hypothesis : P1 - P2 = 0
    
Alternate Hypothesis P1 - P2 != 0

In [45]:
import numpy as np

In [46]:
def two_sample_proportion_test(p1,p2,SE):
    return (p1-p2)/SE

In [47]:
x1 = 53
n1 = 100
x2 = 43
n2 = 100
p = (x1+x2)/(n1+n2)
SE = np.sqrt((p * (1-p))*((1/n1) + (1/n2)))
p1 = x1/ n1
p2 = x2 / n2
z_value = two_sample_proportion_test(p1,p2,SE)
print("Z Value : ",z_value)

Z Value :  1.4153462926807452


We use significance level α = 0.05, but because of a two-sided test we have two rejection regions. They are z < −1.96 or z > 1.96..

In [48]:
if z_value > 1.96 or z_value < -1.96  :
    print("We Reject the Null Hypothesis(HO)")
else :
    print("We Do Not Reject The Null Hypothesis(HO)")

We Do Not Reject The Null Hypothesis(HO)


# Problem Statement 16:

Carry out a one-tailed test to determine whether the population proportion of
traveler’s check buyers who buy at least $2500 in checks when sweepstakes prizes
are offered as at least 10% higher than the proportion of such buyers when no
sweepstakes are on.

Population 1: With sweepstakes

n1 = 300
x1 = 120
𝑝1 = 0.40

Population 2: No sweepstakes 
    
n2 = 700
x2 = 140
𝑝2= 0.20

Null hypothesis : P1 - P2 <= 0.10

Alternate Hypothesis P1 - P2 > 0.10

In [49]:
import numpy as np

In [50]:
def two_sample_proportion_test(p1,p2,SE,D):
    return ((p1-p2)-D)/SE

In [51]:
x1 = 120
n1 = 300
x2 = 140
n2 = 700
p1 = x1/ n1
p2 = x2 / n2
SE = np.sqrt(((p1 * (1-p1))/n1)+((p2 * (1-p2))/n2))
z_value = two_sample_proportion_test(p1,p2,SE,0.10)
print("Z Value : ",z_value)

Z Value :  3.1180478223116177


We use significance level α = 0.001,but because of a one-sided test we have one rejection regions that is z > 3.09.

In [52]:
if z_value > 3.09 :
    print("We Reject the Null Hypothesis(HO)")
else :
    print("We Do Not Reject The Null Hypothesis(HO)")

We Reject the Null Hypothesis(HO)


# Problem Statement 17:

A die is thrown 132 times with the following results: Number turned up: 1, 2, 3, 4, 5, 6
Frequency: 16, 20, 25, 14, 29, 28
Is the die unbiased? Consider the degrees of freedom as 𝑝 −  .

In [53]:
import pandas as pd
import numpy as np

Expected Frequency = 132 / 6 = 22

degree of freedom = n - 1 = 6 - 1 = 5

Null Hypothesis (HO) : The die is unbiased 
    
Alternative Hypothesis (HA): The die is not unbiased.

In [54]:
d = {
    "Ob_frq" : pd.Series([16, 20, 25, 14, 29, 28]),
    "Ex_frq" : pd.Series([22,22,22,22,22,22])
    }
data = pd.DataFrame(d)
data

Ob_frq  Ex_frq
0      16      22
1      20      22
2      25      22
3      14      22
4      29      22
5      28      22

In [55]:
data["(Ob_frq - Ex_frq)^2"] = (data["Ob_frq"] - data["Ex_frq"])**2
data

Ob_frq  Ex_frq  (Ob_frq - Ex_frq)^2
0      16      22                   36
1      20      22                    4
2      25      22                    9
3      14      22                   64
4      29      22                   49
5      28      22                   36

<img src = "https://sites.google.com/site/skillsa229/_/rsrc/1327153749666/chi-squared/chisqu.gif">


In [56]:
chi2_value = sum(data["(Ob_frq - Ex_frq)^2"]) / 22
chi2_value

9.0

Critical value of Chi2 at level of  significance (alpha) = 0.05 and degree of freedom (dof) = 5 is 11.0705

In [57]:
if chi2_value > 11.0705 :
    print("We Reject the Null Hypothesis(HO)")
else :
    print("We Do Not Reject The Null Hypothesis(HO)")

We Do Not Reject The Null Hypothesis(HO)


# Problem Statement 18:

In a certain town, there are about one million eligible voters. A simple random
sample of 10,000 eligible voters was chosen to study the relationship between
gender and participation in the last election. The results are summarized in the
following 2X2 (read two by two) contingency table:
    
We would want to check whether being a man or a woman (columns) is independent of
having voted in the last election (rows). In other words, is “gender and voting independent”?

In [58]:
import pandas as pd
import numpy as np
from scipy import stats

In [59]:
male = [2792,1489]
female = [3591,2131]
votes = male + female
votes

[2792, 1489, 3591, 2131]

In [60]:
sex = ["male","male","female","female"]
status = ["voted","not voted","voted","not voted"]
df = pd.DataFrame({"sex" : sex , "status" : status , "No_of_votes" : votes})
df

sex     status  No_of_votes
0    male      voted         2792
1    male  not voted         1489
2  female      voted         3591
3  female  not voted         2131

In [61]:
dataset_table = pd.crosstab(df["status"],df["sex"],df["No_of_votes"],aggfunc = "sum")
dataset_table

sex        female  male
status                 
not voted    2131  1489
voted        3591  2792

In [62]:
contigency_table = dataset_table.values
print(contigency_table)

[[2131 1489]
 [3591 2792]]


Null Hypothesis : Gender and voting are independent to each other.

Alternate Hypothesis : Gender and voting are dependent to each other.

In [63]:
#observed frequencies
observed_value = contigency_table

In [64]:
#Expected Frequencies
val = stats.chi2_contingency(dataset_table)
val

(6.314589480291856,
 0.011974846738200842,
 1,
 array([[2070.74277717, 1549.25722283],
        [3651.25722283, 2731.74277717]]))

In [65]:
expected_value = val[3]
dof = val[2] #degree of freedom

In [66]:
#perform chi2 test
chi2 = sum(sum([((O - E)**2)/E for O,E in zip(observed_value,expected_value)]))
print("Chi2 value :",chi2)

Chi2 value : 6.420702295825501


In [67]:
#Critical Value
alpha = 0.05
critical_value = stats.chi2.ppf(1-alpha,dof)
print("Critical Value : ",critical_value)

Critical Value :  3.841458820694124


In [68]:
#P Value
p_value = 1 - stats.chi2.cdf(chi2,dof)
print("P Value :",p_value)

P Value : 0.011279754528095265


In [69]:
#Compairing 
if chi2 >= critical_value :
    print("Gender and voting are dependent to each other.")
else :
    print("Gender and voting are independent to each other.")
#compairing p value
if p_value <= alpha :
    print("Gender and voting are dependent to each other.")
else :
    print("Gender and voting are independent to each other.")

Gender and voting are dependent to each other.
Gender and voting are dependent to each other.


# Problem Statement 19:

A sample of 100 voters are asked which of four candidates they would vote for in an
election. The number supporting each candidate is given below:
    
Do the data suggest that all candidates are equally popular? [Chi-Square = 14.96,
with 3 df, 𝑝    0.05 

In [70]:
import pandas as pd
import numpy as np

Expected Frequency = 100 / 5 = 25

degree of freedom = n - 1 = 4 - 1 = 3

Null Hypothesis (HO) : All candidates are equally popular.

Alternative Hypothesis (HA): All candidates are unequally popular

In [71]:
d = {
    "Ob_frq" : pd.Series([41,19,24,16]),
    "Ex_frq" : pd.Series([25,25,25,25])
    }
data = pd.DataFrame(d)
data

Ob_frq  Ex_frq
0      41      25
1      19      25
2      24      25
3      16      25

In [72]:
data["(Ob_frq - Ex_frq)^2"] = (data["Ob_frq"] - data["Ex_frq"])**2
data

Ob_frq  Ex_frq  (Ob_frq - Ex_frq)^2
0      41      25                  256
1      19      25                   36
2      24      25                    1
3      16      25                   81

In [73]:
chi2_value = sum(data["(Ob_frq - Ex_frq)^2"]) / 25
chi2_value

14.96

Critical value of Chi2 at level of significance (alpha) = 0.05 and degree of freedom (dof) = 3 is 7.82

In [74]:
if chi2_value > 7.82 :
    print("We Reject the Null Hypothesis(HO)")
else :
    print("We Do Not Reject The Null Hypothesis(HO)")

We Reject the Null Hypothesis(HO)


# Problem Statement 20:

Children of three ages are asked to indicate their preference for three photographs of
adults. Do the data suggest that there is a significant relationship between age and
photograph preference? What is wrong with this study? [Chi-Square = 29.6, with 4
df: 𝑝 < 0.05].

                Age of child:                              Photograph:
                                      A                      B                      C

                   5-6 years:        18                     22                     20

                   7-8 years:         2                    28                     40

                   9-10 years:       20                     10                     40

In [75]:
import pandas as pd
import numpy as np
from scipy import stats

In [76]:
A = [18,2,20]
B = [22,28,10]
C = [20,40,40]
total = A + B + C
total

[18, 2, 20, 22, 28, 10, 20, 40, 40]

In [77]:
Age_of_child = ["5-6 years","7-8 years","9-10 years","5-6 years","7-8 years","9-10 years","5-6 years","7-8 years","9-10 years"]
photograph = ["A","A","A","B","B","B","C","C","C"]
df = pd.DataFrame({"Age_of_child" : Age_of_child , "Photograph" : photograph , "Total" : total})
df

Age_of_child Photograph  Total
0    5-6 years          A     18
1    7-8 years          A      2
2   9-10 years          A     20
3    5-6 years          B     22
4    7-8 years          B     28
5   9-10 years          B     10
6    5-6 years          C     20
7    7-8 years          C     40
8   9-10 years          C     40

In [78]:
dataset_table = pd.crosstab(df["Photograph"],df["Age_of_child"],df["Total"],aggfunc = "sum")
dataset_table

Age_of_child  5-6 years  7-8 years  9-10 years
Photograph                                    
A                    18          2          20
B                    22         28          10
C                    20         40          40

In [79]:
contigency_table = dataset_table.values
print(contigency_table)

[[18  2 20]
 [22 28 10]
 [20 40 40]]


Null Hypothesis : There is a no significant relationship between age and
photograph preference.

Alternate Hypothesis : There is a significant relationship between age and
photograph preference.

In [80]:
#observed frequencies
observed_value = contigency_table

In [81]:
#Expected Frequencies
val = stats.chi2_contingency(dataset_table)
val

(29.603174603174605,
 5.894582174262628e-06,
 4,
 array([[12., 14., 14.],
        [18., 21., 21.],
        [30., 35., 35.]]))

In [82]:
expected_value = val[3]
dof = val[2] #degree of freedom

In [83]:
#perform chi2 test
chi2 = sum(sum([((O - E)**2)/E for O,E in zip(observed_value,expected_value)]))
print("Chi2 value :",chi2)

Chi2 value : 29.603174603174605


In [84]:
#Critical Value
alpha = 0.05
critical_value = stats.chi2.ppf(1-alpha,dof)
print("Critical Value : ",critical_value)

Critical Value :  9.487729036781154


In [85]:
#P Value
p_value = 1 - stats.chi2.cdf(chi2,dof)
print("P Value :",p_value)

P Value : 5.894582174259533e-06


In [86]:
#Compairing 
if chi2 >= critical_value :
    print("There is a significant relationship between age and photograph preference")
else :
    print("There is a no significant relationship between age and photograph preference")
#compairing p value
if p_value <= alpha :
    print("There is a significant relationship between age and photograph preference")
else :
    print("There is a no significant relationship between age and photograph preference")

There is a significant relationship between age and photograph preference
There is a significant relationship between age and photograph preference


# Problem Statement 21:

A study of conformity using the Asch paradigm involved two conditions: one where
one confederate supported the true judgement and another where no confederate
gave the correct response.

                            Support:                        No Support:

            Conform:           18                                40

            Not Conform:       32                                 10
                
                
Is there a significant difference between the "support" and "no support" conditions in the
frequency with which individuals are likely to conform? [Chi-Square = 19.87, with 1 df:
𝑝 < 0.05]

In [87]:
import pandas as pd
import numpy as np
from scipy import stats

In [88]:
support = [18,32]
No_support = [40,10]
total = support + No_support
total

[18, 32, 40, 10]

In [89]:
row = ["support","support","No support","No support"]
column = ["Conform","Not Conform","Conform","Not Conform"]
df = pd.DataFrame({"Row" : row , "Column" : column , "Total" : total})
df

Row       Column  Total
0     support      Conform     18
1     support  Not Conform     32
2  No support      Conform     40
3  No support  Not Conform     10

In [90]:
dataset_table = pd.crosstab(df["Row"],df["Column"],df["Total"],aggfunc = "sum")
dataset_table

Column      Conform  Not Conform
Row                             
No support       40           10
support          18           32

In [91]:
contigency_table = dataset_table.values
print(contigency_table)

[[40 10]
 [18 32]]


Null Hypothesis : There is no significant difference between the "support" and "no support" conditions in the
frequency with which individuals are likely to conform.

Alternate Hypothesis : There is significant difference between the "support" and "no support" conditions in the
frequency with which individuals are likely to conform.

In [92]:
#observed frequencies
observed_value = contigency_table

In [93]:
#Expected Frequencies
val = stats.chi2_contingency(dataset_table)
val

(18.10344827586207,
 2.092221924065813e-05,
 1,
 array([[29., 21.],
        [29., 21.]]))

In [94]:
expected_value = val[3]
dof = val[2] #degree of freedom

In [95]:
#perform chi2 test
chi2 = sum(sum([((O - E)**2)/E for O,E in zip(observed_value,expected_value)]))
print("Chi2 value :",chi2)

Chi2 value : 19.868637110016422


In [96]:
#Critical Value
alpha = 0.05
critical_value = stats.chi2.ppf(1-alpha,dof)
print("Critical Value : ",critical_value)

Critical Value :  3.841458820694124


In [97]:
#P Value
p_value = 1 - stats.chi2.cdf(chi2,dof)
print("P Value :",p_value)

P Value : 8.29500671717387e-06


In [98]:
#Compairing 
if chi2 >= critical_value :
    print("There is significant difference between the support and no support conditions in the frequency with which individuals are likely to conform")
else :
    print("There is no significant difference between the support and no support conditions in the frequency with which individuals are likely to conform")
#compairing p value
if p_value <= alpha :
    print("There is significant difference between the support and no support conditions in the frequency with which individuals are likely to conform")
else :
    print("There is no significant difference between the support and no support conditions in the frequency with which individuals are likely to conform")

There is significant difference between the support and no support conditions in the frequency with which individuals are likely to conform
There is significant difference between the support and no support conditions in the frequency with which individuals are likely to conform


# Problem Statement 22:

We want to test whether short people differ with respect to their leadership qualities
(Genghis Khan, Adolf Hitler and Napoleon were all stature-deprived, and how many midget
MP's are there?) The following table shows the frequencies with which 43 short people and
52 tall people were categorized as "leaders", "followers" or as "unclassifiable". Is there a
relationship between height and leadership qualities?
[Chi-Square = 10.71, with 2 df: 𝑝 < 0.01].

In [99]:
import pandas as pd
import numpy as np
from scipy import stats

In [100]:
short = [12,22,9]
tall = [32,14,6]
total = short + tall
total

[12, 22, 9, 32, 14, 6]

In [101]:
height = ["short","short","short","tall","tall","tall"]
category = ["leaders","followers","unclassifiable","leaders","followers","unclassifiable"]
df = pd.DataFrame({"Height" : height , "leadership" : category , "Total" : total})
df

Height      leadership  Total
0  short         leaders     12
1  short       followers     22
2  short  unclassifiable      9
3   tall         leaders     32
4   tall       followers     14
5   tall  unclassifiable      6

In [102]:
dataset_table = pd.crosstab(df["Height"],df["leadership"],df["Total"],aggfunc = "sum")
dataset_table

leadership  followers  leaders  unclassifiable
Height                                        
short              22       12               9
tall               14       32               6

In [103]:
contigency_table = dataset_table.values
print(contigency_table)

[[22 12  9]
 [14 32  6]]


Null Hypothesis : There is no relationship between height and leadership qualities

Alternate Hypothesis : There is relationship between height and leadership qualities

In [104]:
#observed frequencies
observed_value = contigency_table

In [105]:
#Expected Frequencies
val = stats.chi2_contingency(dataset_table)
val

(10.712198008709638,
 0.004719280137040844,
 2,
 array([[16.29473684, 19.91578947,  6.78947368],
        [19.70526316, 24.08421053,  8.21052632]]))

In [106]:
expected_value = val[3]
dof = val[2] #degree of freedom

In [107]:
#perform chi2 test
chi2 = sum(sum([((O - E)**2)/E for O,E in zip(observed_value,expected_value)]))
print("Chi2 value :",chi2)

Chi2 value : 10.712198008709638


In [108]:
#Critical Value
alpha = 0.05
critical_value = stats.chi2.ppf(1-alpha,dof)
print("Critical Value : ",critical_value)

Critical Value :  5.991464547107979


In [109]:
#P Value
p_value = 1 - stats.chi2.cdf(chi2,dof)
print("P Value :",p_value)

P Value : 0.0047192801370408155


In [110]:
#Compairing 
if chi2 >= critical_value :
    print("There is relationship between height and leadership qualities")
else:
    print("There is no relationship between height and leadership qualities")
#compairing p value
if p_value <= alpha :
     print("There is relationship between height and leadership qualities")
else:
    print("There is no relationship between height and leadership qualities")

There is relationship between height and leadership qualities
There is relationship between height and leadership qualities


# Problem Statement 23:

Each respondent in the Current Population Survey of March 1993 was classified as
employed, unemployed, or outside the labor force. The results for men in California age 35-
44 can be cross-tabulated by marital status, as follows:
    
Men of different marital status seem to have different distributions of labor force status. Or is
this just chance variation? (you may assume the table results from a simple random
sample.)

In [111]:
import pandas as pd
import numpy as np
from scipy import stats

In [112]:
M = [679,63,42]
W = [103,10,18]
N_M = [114,20,25]
total = M + W + N_M
total

[679, 63, 42, 103, 10, 18, 114, 20, 25]

In [113]:
marital_status = ["Married","Married","Married","Widowed","Widowed","Widowed","Never Married","Never Married","Never Married"]
category = ["Employed","Unemployed","Not in labor force","Employed","Unemployed","Not in labor force","Employed","Unemployed","Not in labor force"]
df = pd.DataFrame({"Marital Status" : marital_status , "labor force status" : category , "Total" : total})
df

Marital Status  labor force status  Total
0        Married            Employed    679
1        Married          Unemployed     63
2        Married  Not in labor force     42
3        Widowed            Employed    103
4        Widowed          Unemployed     10
5        Widowed  Not in labor force     18
6  Never Married            Employed    114
7  Never Married          Unemployed     20
8  Never Married  Not in labor force     25

In [114]:
dataset_table = pd.crosstab(df["Marital Status"],df["labor force status"],df["Total"],aggfunc = "sum")
dataset_table

labor force status  Employed  Not in labor force  Unemployed
Marital Status                                              
Married                  679                  42          63
Never Married            114                  25          20
Widowed                  103                  18          10

In [115]:
contigency_table = dataset_table.values
print(contigency_table)

[[679  42  63]
 [114  25  20]
 [103  18  10]]


Null Hypothesis : There is no relationship between Marital Status and labor force status

Alternate Hypothesis : There is relationship between Marital Status and labor force status

In [116]:
#observed frequencies
observed_value = contigency_table

In [117]:
#Expected Frequencies
val = stats.chi2_contingency(dataset_table)
val

(31.61310319407798,
 2.2949883042859918e-06,
 4,
 array([[654.06331471,  62.04841713,  67.88826816],
        [132.64804469,  12.58379888,  13.76815642],
        [109.2886406 ,  10.36778399,  11.34357542]]))

In [118]:
expected_value = val[3]
dof = val[2] #degree of freedom

In [119]:
#perform chi2 test
chi2 = sum(sum([((O - E)**2)/E for O,E in zip(observed_value,expected_value)]))
print("Chi2 value :",chi2)

Chi2 value : 31.61310319407798


In [120]:
#Critical Value
alpha = 0.05
critical_value = stats.chi2.ppf(1-alpha,dof)
print("Critical Value : ",critical_value)

Critical Value :  9.487729036781154


In [121]:
#P Value
p_value = 1 - stats.chi2.cdf(chi2,dof)
print("P Value :",p_value)

P Value : 2.294988304285539e-06


In [122]:
#Compairing 
if chi2 >= critical_value :
    print("There is relationship between Marital Status and labor force status")
else:
    print("There is no relationship between Marital Status and labor force status")
#compairing p value
if p_value <= alpha :
     print("There is relationship between Marital Status and labor force status")
else:
    print("There is no relationship between Marital Status and labor force status")

There is relationship between Marital Status and labor force status
There is relationship between Marital Status and labor force status
